### ISSUE TITLE
Change component/node color

### ISSUE THREAD

**Issue by borja010** [retejs/examples#10]
Good afternoon,

Is there any way to change the component color or node color on real time in Angular?

Thank you in advance.

**Comment by Ni55aN** [comment]
Yes, use a custom Node.vue 
https://github.com/retejs/rete/issues/209#issuecomment-434406096
https://github.com/retejs/examples/issues/9#issuecomment-436433281

**Comment by borja010** [comment]
Thank you for the quick response.

Im actually using rete-alight-render-plugin since the vue-render-plugin is not properly making the connections. By any chance do you know if there is a way with rete-alight-render-plugin or are you planning to update with the connections working properly?

**Comment by Ni55aN** [comment]
What exactly is wrong with the connection? Render plugins do not affect connections

**Comment by borja010** [comment]
The connections are not matching.

![image](https://user-images.githubusercontent.com/14120800/48288344-70b15380-e431-11e8-851c-7b641fd2e19b.png)

**Comment by Ni55aN** [comment]
What version of `rete-connection-plugin`?

**Comment by borja010** [comment]
Im using the same example that you uploaded. I just do a npm install and try it.
    
"rete": "^1.0.0-beta.5",
"rete-connection-plugin": "^0.2.4",
"rete-vue-render-plugin": "^0.2.4",

**Comment by Ni55aN** [comment]
You need the latest version of rete-connection-plugin (v0.3.1)

**Comment by borja010** [comment]
I just tried with the latest version and it still the same. When you tried by yourself, is working properly? Are you trying it on chrome?

**Comment by Ni55aN** [comment]
Yes, just checked in Chrome 68. https://codepen.io/Ni55aN/pen/xzgQYq

I had a similar issue when SVG width and height are less than 12px. I still do not know exactly the reason for such strange behavior. Try to define the next styles:

```css
svg.connection {
  width: auto;
  height: auto;
}
```

**Comment by borja010** [comment]
I just tried now and its working like a charm.

Thank you very much for the assistance.

Is the example provided for Angular? Im trying to follow the information from https://github.com/retejs/vue-render-plugin and the example but I dont have access to this.data.render and the CustomNodeComponent.

**Comment by borja010** [comment]
Good night,

I have been trying today how to use vue but Im not sure if Im undertanding it properly. Can you share with me an example to change the color form a node.

`import Vue from 'vue/dist/vue.esm';
import { Component, Input, Output } from 'rete';
import { numSocket } from '../sockets';
import { NumControl } from '../controls/number-control';

const VueNode = Vue.component('node', {
    props: [],
    template: '<style>.node background: #ff0000</style>',
    data() {
    },
    methods: {
        
      }
  });

  export class NodeComponent extends Component{
    component: any;
    props: any;
    vueContext: any;
  
    constructor() {
        super('Add');
        this.component = VueNode;
      }
    
      builder(node) {
        const inp1 = new Input('num1', 'Number', numSocket);
        const inp2 = new Input('num2', 'Number', numSocket);
        const out = new Output('num', 'Number', numSocket);
    
        inp1.addControl(new NumControl(this.editor, 'num1'));
        inp2.addControl(new NumControl(this.editor, 'num2'));
    
        node.addInput(inp1)
          .addInput(inp2)
          .addControl(new NumControl(this.editor, 'preview', true))
          .addOutput(out);
      }
    
      worker(node, inputs, outputs) {
        const n1 = inputs['num1'].length ? inputs['num1'][0] : node.data.num1;
        const n2 = inputs['num2'].length ? inputs['num2'][0] : node.data.num2;
        const sum = n1 + n2;
    
        const ctrl = <NumControl> this.editor.nodes.find(n => n.id === node.id).controls.get('preview');
        ctrl.setValue(sum);
        outputs['num'] = sum;
      }
    
      created(node) {
        console.log('created', node);
      }
    
      destroyed(node) {
        console.log('destroyed', node);
      }

  }`

I tried to combine the vue class that you have on the angular example with the add example.

Thank you in advance for the assistance,.

**Comment by borja010** [comment]
Im not sure if Im doing well but the last error that I encountered is:

> ERROR in ./src/app/rete/components/node/Node.vue 1:0
> Module parse failed: Unexpected token (1:0)
> You may need an appropriate loader to handle this file type.
> > <template lang="pug">
> | .node(:class="[selected(), node.name] | kebab")
> |   .title {{node.name}}

Can you please let me know if Im doing it properly and if you encountered this error?

**Comment by borja010** [comment]
I decided to have this on hold and try to add a button with a function that I need to execute. Im using rete-alight-render-plugin. Can you please provide me an example or tell me what is the proper way to do it since I already added the click event and bind it but it still not working.

**Comment by Ni55aN** [comment]
> the canvas is created and it return the node to the initial status

can you describe in detail?

**Comment by borja010** [comment]
I was already able to fix it by adding a container in the creation of the personalized node. Thank you for the reply and the follow up. Ill be closing this issue since by being able to create my own node, it opens a lot of possibilities.
