### ISSUE TITLE
Dragging all connected nodes

### ISSUE THREAD

**Issue by borja010** [retejs/examples#13]
Good evening,

Is there any way to move at the same time all the connected nodes?

Right now Im able to change the position from the nodes but they just update the view until I select each one of them, how can I refresh the whole view or all the nodes?

Thank you in advance for the assistance.

**Comment by Ni55aN** [comment]
You can create plugin: subscribe to `nodetranslated` event, get connections from `node.getConnections();` and translate connected nodes.

But how should it be active? When you press a key? Maybe it's better to just select multiple nodes and move them at the same time?

**Comment by borja010** [comment]
I added a button in order to collapse all the nodes that are related:
![image](https://user-images.githubusercontent.com/14120800/49541433-65b6db00-f898-11e8-8f09-2f7eb0fcb18c.png)

And when the nodes are collapse and I move the node, all the hidden nodes needs to move along with the node that the hidden button pressed.

**Comment by borja010** [comment]
I was already able to do it by refreshing all the connections.
