### ISSUE TITLE
Removing Outputs Dinamically

### ISSUE THREAD

**Issue by borja010** [retejs/examples#14]
Good afternoon,

Im removing an output dynamically but using the removeOutput method from the node but Im having the following error:

![image](https://user-images.githubusercontent.com/14120800/49541221-c1349900-f897-11e8-85e2-56a2166d5532.png)

After reviewing the libraries and trying to figure out what is wrong, it seems to be that the socket from the output is not being removed and even after updating the node, when we click the socket its still grabbing the previous name from the html.

Do you know how can I fix this?

Thank you in advance.

**Comment by Ni55aN** [comment]
Is the problem resolved?

**Comment by borja010** [comment]
Yes I was able to resolve it by cloning the node, but you should check why when you remove an output from a node, it does not update the html and the sockets.
