### ISSUE TITLE
Remove "You are running Vue in development mode" in angular

### ISSUE THREAD

**Issue by testermax** [retejs/examples#18]
Hi,

Is there a way of removing the following text in the console, when running with angular renderer i development mode?

> You are running Vue in development mode.
> Make sure to turn on production mode when deploying for production.
> See more tips at https://vuejs.org/guide/deployment.html

I dont have any Vue libraries in my package.json and I dont understand why this print in the console is there in the first place.

**Comment by vamidi** [comment]
I have the same thing and there production is not building anymore.

**Comment by Ni55aN** [comment]
`rete-context-menu-plugin` use Vue.js
