### ISSUE TITLE
Flow diagram not shown

### ISSUE THREAD

**Issue by dglavask** [retejs/examples#6]
Hi,

I am using angular5 with express.js. I have basically copied and pasted the example project in my angular application but the flow diagram is not showing in the browser. If I inspect the html page then I can see that the elements are being rendered but they are "invisible" in the browser.

**Comment by Ni55aN** [comment]
Do you use [this](https://github.com/Ni55aN/D3NE-examples/blob/master/Angular/src/app/d3ne/d3ne.component.ts) component ?

**Comment by dglavask** [comment]
Hi Yes! The problem is with the css. I can see all the elements but the CSS is not getting applied.

**Comment by dglavask** [comment]
![capture](https://user-images.githubusercontent.com/2270624/38552183-a46a292c-3cbb-11e8-9ce7-fb6f1ab658ad.PNG)

**Comment by Ni55aN** [comment]
Are you sure you have `encapsulation: ViewEncapsulation.None` and correctly linked styles in `styleUrls`?

**Comment by dglavask** [comment]
here is my d3ne component:
`/// <reference path="../../../../node_modules/d3-node-editor/src/index.d.ts"/>
import { Component, AfterViewInit, OnChanges, ViewChild, ElementRef, Input, ViewEncapsulation } from '@angular/core';

@Component({
  selector: 'app-d3ne',
  //templateUrl: './d3ne.component.html',
  template: '<div class="wrapper"><div #d3neEditor class="node-editor"></div></div>',
  styleUrls: ["../../../../node_modules/d3-node-editor/build/d3-node-editor.css", './d3ne.component.css'],
  encapsulation: ViewEncapsulation.None
`})``



All the css files are in place and the ts/js files referenced in angluar-cli config file. If the encapsulation is turned on then nothing gets rendered and I see on message in the javascript console:

undefined d3-node-editor.js:3132

**Comment by Ni55aN** [comment]
Is the correct path to d3-node-editor.css inside `styleUrls`?
Try [this method](https://stackoverflow.com/questions/40071845/how-to-import-css-from-node-modules-in-webpack-angular2-app)

**Comment by sw-ms-jayeshtankariya** [comment]
I tried above method. it is still not working.
any other updates on this?

**Comment by sw-ms-jayeshtankariya** [comment]
I tried with both scenario. 
1) importing in style.css file
2) coping referenced css file content and pasted in component.css

none is working. i guess there is problem with some inbuilt function such that it is not applying any calculations after applying css file

**Comment by sw-ms-jayeshtankariya** [comment]
Quick update :
There is problem with below css class :
.node-editor .connections {
    position: absolute;
    overflow: visible;
    pointer-events: none; }

If you remove this from d3-node-editor.css file, it will atleast render graph without connections
