### ISSUE TITLE
Output Error at Angular example (trying with rete@1.0.0-beta.4)

### ISSUE THREAD

**Issue by robsimal** [retejs/examples#9]
Hello.

I am trying to update the Angular example to rete@1.0.0-beta.4

I have had to update the arguments to create AddComponent and NumComponent:

`const out1 = new Output('num', 'Number', numSocket);
`
`const inp1 = new Input('num1', 'Number', numSocket);
const inp2 = new Input('num2', 'Number', numSocket);
`
I have had to add the 'key' to 'super()' at NumControl constructor:
`super(key);`

And I have had to add a 'key' to the NumControl for AddComponent:
`node.addControl(new NumControl(this.editor, 'preview', true))`

When I try to run ($ng serve) it returns me an error:
`ERROR Error: "Uncaught (in promise): TypeError: Value of argument "output" violates contract
Expected:
Output
Got:
void`

I have found that this error rises at 'rete.component.ts' at the connection of the components:
`editor.connect(n1.outputs[0], add.inputs[0]);`
`editor.connect(n2.outputs[0], add.inputs[1]);`
(I have tried `editor.connect(n1.outputs['num'], add.inputs['num1']);`... as well).

I have checked the outputs of the objects of NumComponent and AddComponent, and they are not null or void.

**Comment by Ni55aN** [comment]
I have update example, but it has the issue with using Vue components in runtime

**Comment by robsimal** [comment]
I have an error with vueContext:
`"this.vueContext is undefined"`
(from `NumControl` > `setValue(val)`, when we try to do     `this.vueContext.value = val;`
)

Is that related to the issue with using Vue?

**Comment by robsimal** [comment]
Also, I have another issue in compiling time:
`"Property 'get' does not exist on type 'Control[]'."`
At `AddComponent` > `worker(...)` > `    this.editor.nodes.find(n => n.id == node.id).controls.get('preview').setValue(sum);`

It does not allow me to use .get() function to get the control from `controls`

**Comment by Ni55aN** [comment]
Please update to rete@1.0.0-beta.5

**Comment by Ni55aN** [comment]
> setValue

It looks like you call a `setValue` after instance initialization and before component mounted.
[Solution](https://github.com/retejs/rete.js.org/blob/master/src/rete/controls/field/index.js): put the initial value to props before the `vueContext` created

**Comment by robsimal** [comment]
Hello.
Thanks for the information; I have been able to solve that issues.

However, there is still a problem with Vue when executing: 
`[Vue warn]: You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.`

What I have found at some forums is that Vue must be imported as: `import Vue from 'vue/dist/vue.js'` instead of `import Vue from 'vue'`

Could I use AlightRenderPlugin render instead of VueRenderPlugin? Is there any example on how can I use it, "translatable" to Angular version?

Thanks.

**Comment by robsimal** [comment]
I have succeed to adapt it to AligthRenderPlugin, but nodes connections are not passing data:
"AddComponent.worker(...):  n1: undefined , n2: undefined"...
I have compared the code with the Angular code for rete@1.0.0-alpha2 (which is running properly), and I found almost no difference. Then, I guess that the "data flow" is not working for the latest version of rete yet.

Should I better use rete@1.0.0-alpha2 version for the time being?

**Comment by Ni55aN** [comment]
I'll try to fix it in the latest version. There is one issue - imported Vue in vue-render-plugin doesn't allow to compile template at runtime

**Comment by Ni55aN** [comment]
For now, you can use alight-render-plugin for controls rendering (controls must have a this.render="alight", and components - this.render='vue').

I have tried alias to `vue/dist/vue.js` in vue-render-plugin, but but it didn't work for some reason. Another solution is to somehow setup Vue single-file components into Angular project.

**Comment by Ni55aN** [comment]
I found the solution, but it all attempts to integrate vue-loader into Angular project are unsuccessful.
```js
import Vue from 'vue/dist/vue.esm';

const comp = Vue.component('num' { ... vue component propeerties });
```
Example:
```js
import Vue from 'vue/dist/vue.esm';

const VueNumControl = Vue.component('num', {
  props: ['readonly', 'emitter', 'ikey', 'getData', 'putData'],
  template: '<input type="number" :readonly="readonly" :value="value" @input="change($event)"/>',
  data() {
    return {
      value: 0,
    };
  },
  methods: {
    change(e) {
      this.value = +e.target.value;
      this.update();
    },
    update() {
      if (this.ikey) {
        this.putData(this.ikey, this.value);
      }
      this.emitter.trigger('process');
    }
  },
  mounted() {
    this.value = this.getData(this.ikey);
  }
});
```
